eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka:eureka@49.233.48.181:8761/eureka # 注册地址
  instance:
    instance-id: mall-zuul # eureka显示的路径名称
    prefer-ip-address: true # 注册客户端时，使用ip地址注册而不是hostname
spring:
  application:
    name: mall-zuul
  cloud:
    sentinel:
      transport:
        port: 8719  # 启动一个httpServer与sentinel dashboard进行交互
        dashboard: localhost:9000
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8000
zuul:
  routes:
    mall-user-service: /user-service/**
    mall-order-service: /order-service/**
  ignored-services: "*"
  retryable: true
ribbon:
  ReadTimeout: 2500
  ConnectTimeout: 1000
  MaxAutoRetries: 2 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000