eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka:eureka@49.233.48.181:8761/eureka # 注册地址
  instance:
    instance-id: mall-user-service # eureka显示的路径名称
    prefer-ip-address: true # 注册客户端时，使用ip地址注册而不是hostname
spring:
  application:
    name: mall-user-service
  datasource:
    druid:
      url: jdbc:mysql://49.233.48.181:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  cloud:
    sentinel:
      transport:
        port: 8719  # 启动一个httpServer与sentinel dashboard进行交互
        dashboard: localhost:9000
  redis:
    host: 49.233.48.181
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.mall.user.mapper: debug
feign:
  hystrix:
    enabled: false
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
auth:
  server-uri: http://localhost:8111
security:
  oauth2:
#    client:
#      client-id: user-client
#      client-secret: user-secret-8888
#      user-authorization-uri: ${server-uri}/oauth/authorize
#      access-token-uri: ${auth.server-uri}/oauth/token
#    authorization:
#      check-token-access: ${auth.server-uri}/oauth/check_token
    resource:
      id: user-client
      user-info-uri: ${auth.server-uri}/user/me