eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      #defaultZone: http://localhost:8761/eureka # 注册地址
      defaultZone: http://eureka:eureka@49.233.48.181:8761/eureka # 注册地址
  instance:
    instance-id: mall-user-service # eureka显示的路径名称
    prefer-ip-address: true # 注册客户端时，使用ip地址注册而不是hostname
spring:
  application:
    name: mall-user-service
  datasource:
    druid:
      url: jdbc:mysql://49.233.48.181:3306/mall?useUnicode=true&characeterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml