eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka:eureka@49.233.48.181:8761/eureka # 注册地址
  instance:
    prefer-ip-address: true # 注册客户端时，使用ip地址注册而不是hostname
spring:
  application:
    name: mall-order-service
  datasource:
    druid:
      url: jdbc:mysql://49.233.48.181:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  redis:
    host: 49.233.48.181
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  main:
    allow-bean-definition-overriding: true #多个相同name的feign客户端需要启用这个配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.mall.order.mapper: debug
pagehelper:
  helper-dialect: mysql
management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    resource:
      id: order-client
      user-info-uri: /user/me